// Stub module for AI photo functionality
// TODO: Implement full AI integration

export const AI_AUTO_GENERATED_FIELDS_ALL = [
  'title',
  'caption',
  'tags',
  'description',
  'semantic',
] as const;

export type AIAutoGeneratedField = typeof AI_AUTO_GENERATED_FIELDS_ALL[number];

export const cleanUpAiTextResponse = (text: string): string => {
  // Stub implementation
  return text.trim();
};
